[package]
name = "guardian"
version = "0.1.0"
authors = ["Hao Shi <shisoftgenius@gmail.com>"]

[dependencies]
clap = "*"
parking_lot = "*"
stopwatch = "*"
procinfo = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"